import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FullLayout from "@/components/layouts/FullLayout";
import { StoreProvider } from "@/redux/storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
            {/* <FullLayout> */}
            <body className={inter.className}>
              {children}
            </body>
            {/* </FullLayout> */}
      </html>
    </StoreProvider>
  );
}
