import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FullLayout from "@/components/layouts/FullLayout";
import { StoreProvider } from "@/redux/storeProvider";
import { Toaster } from "sonner"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            {/* <FullLayout> */}
            <body className={inter.className}>
              <StoreProvider>
                  {children}
              </StoreProvider>
              <Toaster richColors  duration={5000}/>
            </body>
            {/* </FullLayout> */}
      </html>
  );
}
